#obj-m += lte_ncm.o
obj-m += lc_ltencm.o


#lte_ncm-objs := lte-ncm.o partialbuf.o dhcp.o arp.o filter.o dhcp_dev_info.o dhcpv6.o icmpv6.o ipv6.o
lc_ltencm-objs := lte-ncm.o partialbuf.o dhcp.o arp.o filter.o dhcp_dev_info.o dhcpv6.o icmpv6.o ipv6.o

