#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh
. /etc/setled.sh
H_on
mpath=`cat /etc/play/mpath`

logger "$BUTTON pressed for $SEEN seconds"
echo "$BUTTON pressed for $SEEN seconds" > /dev/console

if [ "$SEEN" -lt 1 ]
then
   case ${mpath} in
	0|1|2|3|4|5|6|7|8)
		let mpath+=1
		echo ${mpath} > /etc/play/mpath
		write${mpath}
		;;
	9)
		let mpath=\0xA
		echo A > /etc/play/mpath
		writeA
		;;
	A)
		let mpath=\0xB
		echo B > /etc/play/mpath
		writeB
		;;
	B)
		let mpath=\0xC
		echo C > /etc/play/mpath
		writeC
		;;
	C)
		let mpath=\0xD
		echo D > /etc/play/mpath
		writeD
		;;
	D)
		let mpath=\0xE
		echo E > /etc/play/mpath
		writeE
		;;
	E)
		let mpath=\0xF
		echo F > /etc/play/mpath
		writeF
		;;
	F)
		let mpath=\0xF
		echo F > /etc/play/mpath
		writeF
		;;
   esac
	
write${mpath}


fi



