#!/bin/sh

echo "Content-Type:text/html"
echo ""
echo ""
#echo $QUERY_STRING
#	ssid=`echo $QUERY_STRING | cut -d'&' -f 1 | cut -d'=' -f 2`
#	passwd=`echo $QUERY_STRING | cut -d'&' -f 2 | cut -d'=' -f 2`
#       enc=`echo $QUERY_STRING | cut -d'&' -f 3 | cut -d'=' -f 2`
#	channel=`echo $QUERY_STRING | cut -d'&' -f 4 | cut -d'=' -f 2`
  uci set wireless.@wifi-iface[0].ssid=$WWW_ssid
# uci set wireless.@wifi-iface[0].encryption=$enc
  uci set wireless.@wifi-iface[0].key=$WWW_passwd
  uci set wireless.radio0.channel=$WWW_channel
  uci set wireless.@wifi-iface[0].network=lan
  uci set wireless.@wifi-iface[0].mode=ap
#uci set wireless.@wifi-iface[0].wds=1
  uci commit wireless
  uci set network.lan.ipaddr=192.168.2.1
  uci commit network

echo  "Set AP OK!<br />"
  /etc/init.d/network restart

