#!/bin/sh
#
# Copyright (C) 2011 OpenWrt.org
#

uci set network.4g=interface
uci set network.4g.proto=dhcp
uci set network.4g.ifname=eth2

uci set network.pptp=interface
uci set network.pptp.proto=pptp

uci set network.l2tp=interface
uci set network.l2tp.proto=l2tp
uci commit network
uci set firewall.@zone[1].network="wan wan6 4g pptp l2tp"
uci commit firewall

