#!/bin/sh /etc/rc.common
# Copyright (C) 2011 OpenWrt.org

START=99

start(){
/usr/shellgui/progs/qos_shellgui start
}

stop(){
/usr/shellgui/progs/qos_shellgui stop
}
restart(){
/usr/shellgui/progs/qos_shellgui stop
/usr/shellgui/progs/qos_shellgui start
}

