#!/bin/sh /etc/rc.common

START=99
STOP=99

start() {
sleep 3
	iic > /dev/null 2>&1 &
	sleep 2
	iic2 > /dev/null 2>&1 &
echo 39 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio39/direction
echo 1 > /sys/class/gpio/gpio39/value

}

stop() {
	killall iic
	killall iic2
}
