#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=99
USE_PROCD=1

start_service() {
	base_dir="/usr/shellgui/shellguilighttpd/www/apps/shadowsocks"
	config_str=$(cat $base_dir/shadowsocks.json)
	echo "$config_str" | jshon -e "server" -e "data" >/tmp/etc/ss-server.json
	procd_open_instance
	procd_set_param command /usr/bin/ss-server -c /tmp/etc/ss-server.json
	procd_set_param respawn
	procd_close_instance
}

stop_service() {
	killall ss-redir
}
