#!/bin/sh
#
# Copyright (C) 2011 OpenWrt.org
#

uci set network.4g=interface
uci set network.4g.device='/dev/ttyUSB1'
uci set network.4g.proto='3g'
uci set network.4g.service='umts'
uci set network.4g.apn='3gnet'
uci set network.4g.pincode=''
uci set network.4g.username=''
uci set network.4g.password=''
uci set network.4g.dialnumber='*99#'

uci set network.pptp=interface
uci set network.pptp.proto=pptp

uci set network.l2tp=interface
uci set network.l2tp.proto=l2tp
uci commit network
uci set firewall.@zone[1].network="wan wan6 wwan 4g pptp l2tp"
uci commit firewall
