#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

SERVICE_USE_PID=1

START=50

start() {
	[ -d /var/log/shellguilighttpd ] || mkdir -p /var/log/shellguilighttpd
	chmod 0777 /var/log/shellguilighttpd
	service_start /usr/shellgui/shellguilighttpd/sbin/shellguilighttpd -f /usr/shellgui/shellguilighttpd/etc/lighttpd/lighttpd.conf
}

stop() {
	service_stop /usr/shellgui/shellguilighttpd/sbin/shellguilighttpd
}

