#!/bin/sh

if [ -f /etc/sysctl.conf ] && [ "$ACTION" = add ]; then
	sed -ne "/^[[:space:]]*net\..*\.$DEVICENAME\./p" /etc/sysctl.conf | \
		sysctl -e -p - | logger -t sysctl
fi

[ "$ACTION" = add ]  && {
	if [ "$DEVICENAME" = eth2 ];then
	/etc/init.d/config4g restart
	fi
}