#!/bin/sh

uci set gargoyle.global.fallback_lang=English-EN
uci set gargoyle.global.language=English-EN
uci commit

mv /www/firstboot.i18n.asp /www/firstboot.asp

. /usr/lib/gargoyle/i18nServices.asp
change_menu_language "English-EN"
restart_lang_services
